sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install tox coveralls
before_script:
    - coverage erase
script: tox
after_success:
    - coveralls
notifications:
  email:
    - sinkler@sinkler.ru
