sudo: false
dist: xenial
language: python
matrix:
  include:
    - env: TOXENV=py37-django-master
      python: 3.7
    - env: TOXENV=py36-django-master
      python: 3.6
    - env: TOXENV=py37-django-22
      python: 3.7
    - env: TOXENV=py36-django-22
      python: 3.6
    - env: TOXENV=py36-django-21
      python: 3.6
    - env: TOXENV=py36-django-20
      python: 3.6
    - env: TOXENV=py27-django-111
      python: 2.7
    - env: TOXENV=py36-django-111
      python: 3.6
    - env: TOXENV=py27-django-110
      python: 2.7
    - env: TOXENV=py35-django-110
      python: 3.5
    - env: TOXENV=py27-django-19
      python: 2.7
    - env: TOXENV=py35-django-19
      python: 3.5
    - env: TOXENV=py27-django-18
      python: 2.7
    - env: TOXENV=py35-django-18
      python: 3.5
    - env: TOXENV=py27-django-17
      python: 2.7
    - env: TOXENV=py34-django-17
      python: 3.4
  allow_failures:
    - env: TOXENV=py36-django-master
    - env: TOXENV=py37-django-master
install:
  - pip install tox codecov
before_script:
  - coverage erase
script: tox
after_success:
  - codecov
notifications:
  email:
    - sinkler@sinkler.ru
